name: On merging *-rc PR create PR to dev and merges if possible
on:
  pull_request:
    types: [closed]

jobs:
  after-rc-merged:
    if: ${{ contains(github.event.pull_request.base.ref, '-rc') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Create PR
        id: create_pr
        uses: poorva17/create-pr-action@v2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ github.base_ref }}
          BASE_BRANCH: dev
      - name: Get PR number
        id: get_pr
        run: |
          pr_number=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository_owner }}:${{ github.base_ref }}" \
            | jq '.[0].number')
          echo "::set-output name=number::$pr_number"
      - name: Merge PR
        run: |
          curl -X PUT -H "Authorization: Bearer ${{ secrets.DEV_BE_GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.base_ref }}/merge
