name: On merging *-rc PR create PR to dev
on:
  pull_request:
    types: [closed]

jobs:
  after-rc-merged:
    if: ${{ contains(github.event.pull_request.base.ref, '-rc') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Create new branch
        run: |
          git checkout -b ${{ github.head_ref }}-to-dev-gh-action
          git push origin ${{ github.head_ref }}-to-dev-gh-action
      - name: Create PR
        uses: poorva17/create-pr-action@v2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ github.head_ref }}-to-dev-gh-action
          BASE_BRANCH: dev
