name: On merging *-rc PR create branch and if no conflicts merge to dev
on:
  pull_request:
    types: [closed]

jobs:
  after-rc-merged:
    if: ${{ contains(github.event.pull_request.base.ref, '-rc') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Create PR to dev
        uses: peter-evans/create-pull-request@v5
        with:
          base: ${{ github.head_ref }}
          branch: dev
          title: GH Action ${{ github.head_ref }} to dev
          body: Automatically created PR after merge to ${{ github.base_ref }}.
