name: On merging *-rc PR create PR to dev and merges if possible
on:
  pull_request:
    types: [closed]

jobs:
  after-rc-merged:
    if: ${{ contains(github.event.pull_request.base.ref, '-rc') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Create PR
        uses: poorva17/create-pr-action@v2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ github.base_ref }}
          BASE_BRANCH: dev
      - name: Auto-Merge Pull Request
        uses: reitermarkus/automerge@v2.6.0
